import { Poppins } from "next/font/google";
import "./globals.css";
import SnackbarWrapper from "./utils/snackbarWrapper";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "AI SDR",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${poppins.variable}`}>
        <SnackbarWrapper>
            {children}
        </SnackbarWrapper>
      </body>
    </html>
  );
}
